
import React from 'react';
import { Lightbulb, TrendingUp, AlertTriangle, ArrowRight, Printer, Bot } from 'lucide-react';
import { MOCK_INSIGHTS } from '../constants';
import { StrategicInsight } from '../types';
import { triggerCricket } from '../utils/chatUtils';

interface StrategicInsightsProps {
  insights?: StrategicInsight[];
}

export const StrategicInsights: React.FC<StrategicInsightsProps> = ({ insights = MOCK_INSIGHTS }) => {
  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
           <h2 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight drop-shadow-sm flex items-center gap-2">
             <TrendingUp className="text-emerald-600 dark:text-emerald-400" /> Strategic Insights
           </h2>
           <p className="text-sm text-slate-600 dark:text-slate-400 mt-1 font-medium">AI-driven analysis to optimize fleet mix, increase revenue, and reduce risk.</p>
        </div>
      </div>

      {insights.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {insights.map((insight) => (
            <InsightCard key={insight.id} insight={insight} />
            ))}
        </div>
      ) : (
          <div className="p-8 text-center bg-white/60 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 backdrop-blur-sm">
              <p className="text-slate-500 dark:text-slate-400 italic">No strategic insights currently generated by AI engine.</p>
          </div>
      )}
    </div>
  );
};

const InsightCard: React.FC<{ insight: StrategicInsight }> = ({ insight }) => {
  const isOpportunity = insight.type === 'OPPORTUNITY';
  const isRisk = insight.type === 'RISK';
  
  const borderColor = isOpportunity ? 'border-emerald-400/50' : isRisk ? 'border-red-400/50' : 'border-blue-400/50';
  const glowColor = isOpportunity ? 'shadow-[0_0_20px_rgba(16,185,129,0.15)]' : isRisk ? 'shadow-[0_0_20px_rgba(239,68,68,0.15)]' : 'shadow-[0_0_20px_rgba(59,130,246,0.15)]';
  const iconBg = isOpportunity ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400' : isRisk ? 'bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400' : 'bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400';

  const handleAnalysis = () => {
    triggerCricket(`Analyze the '${insight.title}' regarding ${insight.customer}. What strategic actions should I take to address this ${insight.type.toLowerCase()}?`);
  };

  return (
    <div className={`bg-white/60 dark:bg-slate-800/60 backdrop-blur-xl rounded-xl border ${borderColor} p-6 shadow-md hover:-translate-y-1 transition-all duration-300 group hover:${glowColor} flex flex-col h-full hover:bg-white/80 dark:hover:bg-slate-800/80`}>
      <div className="flex justify-between items-start mb-4">
         <div className={`p-3 rounded-xl ${iconBg} shadow-inner`}>
            {isOpportunity ? <Lightbulb size={24} /> : isRisk ? <AlertTriangle size={24} /> : <TrendingUp size={24} />}
         </div>
         <span className={`text-[10px] font-extrabold uppercase tracking-wider px-2 py-1 rounded-full border ${
            isOpportunity ? 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-700/50 text-emerald-700 dark:text-emerald-400' : 
            isRisk ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-700/50 text-red-700 dark:text-red-400' : 
            'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-700/50 text-blue-700 dark:text-blue-400'
         }`}>
            {insight.type}
         </span>
      </div>

      <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-2 leading-tight group-hover:text-emerald-800 dark:group-hover:text-emerald-400 transition-colors">
        {insight.title}
      </h3>
      
      <p className="text-sm text-slate-600 dark:text-slate-400 mb-6 flex-1 font-medium leading-relaxed">
        {insight.description}
      </p>

      <div className="bg-white/50 dark:bg-slate-700/30 rounded-lg p-3 border border-slate-200/60 dark:border-slate-600/60 mb-4 grid grid-cols-2 gap-4">
         <div>
            <span className="text-[10px] text-slate-400 dark:text-slate-500 uppercase font-extrabold tracking-wider">Projected Impact</span>
            <div className={`text-lg font-mono font-bold ${isRisk ? 'text-red-600 dark:text-red-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
                {insight.impact}
            </div>
         </div>
         <div className="text-right">
            <span className="text-[10px] text-slate-400 dark:text-slate-500 uppercase font-extrabold tracking-wider">Key Metric</span>
            <div className="text-sm font-medium text-slate-700 dark:text-slate-300 font-mono mt-1">
                {insight.metric}
            </div>
         </div>
      </div>

      <div className="flex items-center justify-between pt-4 border-t border-slate-200/50 dark:border-slate-700/50 mt-auto">
         <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400 font-bold">
            {insight.deviceType === 'ROBOT' ? <Bot size={14} /> : <Printer size={14} />}
            {insight.customer}
         </div>
         <button 
            onClick={handleAnalysis}
            className="text-xs font-bold text-slate-600 dark:text-slate-300 hover:text-emerald-600 dark:hover:text-emerald-400 flex items-center gap-1 transition-colors uppercase tracking-wide"
         >
            View Details <ArrowRight size={12} />
         </button>
      </div>
    </div>
  );
};
