
import { AnalysisResult, DiagnosticStatus, VisualAuditSession } from '../types';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

type jsPDFWithAutoTable = any;

const sanitizeFilename = (name: string) => name.replace(/[^a-z0-9]/gi, '_').toLowerCase();

const downloadFile = (content: string, filename: string, contentType: string) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
};

export const generateJsonReport = (data: AnalysisResult, visualSession?: VisualAuditSession) => {
  const jsonString = JSON.stringify({
    metadata: {
      generatedBy: "Crickets Continuum | Fleet Conformance Engine",
      date: new Date().toISOString(),
      version: "2.6"
    },
    diagnosticResult: data,
    visualAudit: visualSession
  }, null, 2);

  downloadFile(jsonString, `Fleet_Audit_Result_${sanitizeFilename(data.documentTitle)}.json`, 'application/json');
};

export const generateMarkdownReport = (data: AnalysisResult, visualSession?: VisualAuditSession) => {
  const date = new Date().toLocaleDateString();
  let report = `# FLEET CONFORMANCE REPORT\n**Target:** ${data.documentTitle}\n**Date:** ${date}\n**Integrity Score:** ${data.complianceScore}/100\n\n## EXECUTIVE SUMMARY\n${data.summary}\n\n`;

  if (visualSession && visualSession.snapshots.length > 0) {
    report += `## VISUAL AUDIT FINDINGS\n`;
    visualSession.snapshots.forEach((s, i) => {
      report += `### Snapshot ${i + 1} (${s.timestamp})\n`;
      if (s.ocrText) report += `- **OCR Detection:** ${s.ocrText}\n`;
      if (s.detectedObjects) report += `- **Objects Found:** ${s.detectedObjects.map(o => o.type).join(', ')}\n`;
      report += `\n`;
    });
  }

  report += `## DIAGNOSTIC FINDINGS\n`;
  data.items.forEach((item, index) => {
    const statusIcon = item.status === DiagnosticStatus.OPTIMAL ? '✅' : item.status === DiagnosticStatus.ISSUE_DETECTED ? '❌' : 'ℹ️';
    report += `\n### ${index + 1}. ${statusIcon} ${item.title}\n- **Status:** ${item.status}\n- **Priority:** ${item.priority || 'N/A'}\n- **Description:** ${item.description}\n- **Standard Reference:** ${item.reference}\n`;
    if (item.recommendation) report += `- **Remediation:** ${item.recommendation}\n`;
  });

  report += `\n---\nGenerated by Crickets Continuum DCA | Autonomous Fleet Compliance\n`;
  downloadFile(report, `Fleet_Report_${sanitizeFilename(data.documentTitle)}.md`, 'text/markdown');
};

export const generatePdfReport = (data: AnalysisResult, visualSession?: VisualAuditSession) => {
  const doc = new jsPDF() as jsPDFWithAutoTable;
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFillColor(15, 23, 42); 
  doc.rect(0, 0, 210, 40, 'F');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255); 
  doc.setFont('helvetica', 'bold');
  doc.text("FLEET AUDIT REPORT", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(255, 184, 0); // Solaris Gold
  doc.text(`Crickets Continuum DCA | Date: ${date}`, 14, 28);

  // Score Badge
  doc.setFillColor(255, 255, 255); 
  doc.roundedRect(160, 10, 35, 20, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text("FLEET SCORE", 164, 16);
  doc.setFontSize(14);
  doc.text(`${data.complianceScore}/100`, 170, 24);

  let currentY = 50;
  
  // Executive Summary
  doc.setFillColor(248, 250, 252); 
  doc.roundedRect(14, currentY, 182, 30, 2, 2, 'F');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text("EXECUTIVE SUMMARY", 18, currentY + 8);
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(doc.splitTextToSize(data.summary, 170), 18, currentY + 16);
  currentY += 40;

  // Visual snapshots (if any)
  if (visualSession && visualSession.snapshots.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text("VISUAL EVIDENCE", 14, currentY);
    currentY += 8;
    
    visualSession.snapshots.slice(0, 3).forEach((s, idx) => {
        try {
            doc.addImage(s.imageUrl, 'JPEG', 14 + (idx * 60), currentY, 55, 40);
        } catch (e) {}
    });
    currentY += 50;
  }

  const tableBody = data.items.map(item => [
    item.status.replace('_', ' '),
    item.priority || '-',
    item.title,
    item.description + (item.recommendation ? `\n\nREMEDIATION: ${item.recommendation}` : '')
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['STATUS', 'PRIORITY', 'AUDIT NODE', 'DETAILS & REMEDIATION']],
    body: tableBody,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255 },
    columnStyles: { 0: { cellWidth: 25 }, 1: { cellWidth: 20 }, 2: { cellWidth: 40 } }
  });

  doc.save(`Fleet_Audit_${sanitizeFilename(data.documentTitle)}.pdf`);
};
